### PR TITLE
refactored expand query function

### PR DESCRIPTION
**Pull request by haochenuw**
This works on my machine -- try it out?

### CODE REVIEW

**Comment by kzhong130** [comment]
Hi, can I know what OS you are using, macOS or ubuntu and the SEAL version?  I am trying out using a vm with ubuntu 16.04, the second run will still fail mysteriously... But I also asked my friend to run on his mac, but it just worked fine. Also, both of us are using branch 3.5.6. Thanks!

**Comment by haochenuw** [comment]
Good point -- I'm on macOS and using SEAL3.5.9. Don't know why it's failing on ubuntu. Have you tried integrating my change into 3.2.0 and try there?

**Comment by kzhong130** [comment]
Sorry for getting back late. I have tried (1) using SEAL 3.5.9 on ubuntu 16.04 with the refactored codes, the second run still showed some errors. (2) using SEAL 3.2.0 with integrated with the change on ubuntu 16.04, the second run also showed segmentation fault. I did these experiments on a brand new virtual machine with ubuntu 16.04, cmake 3.13.0, g++/gcc 7.5.0. 

Also, I notice that the previous version of expand_query from sealPIR seems also showed segmentation fault even in macOS. I try to understand the what the refactored codes change. It seems nearly the same as the original one?

More specifically, I think the main difference you add an apply_galois function on `line 108`, results are stored into `tempctxt_rotatedshifted`. But immediately after this call, you call `multiply_power_of_X(tempctxt_rotated, tempctxt_rotatedshifted, index, params)` on line 111. Then `tempctxt_rotatedshifted` is overwritten by the result of `multiply_power_of_X` function? So seems that `apply_galois` on `line 108` is not doing anything useful. If so, I think `expand_query` is doing exactly the same thing as the original one, with different ways/places to store the ciphertexts.

So I am curious why the previous approach does not work while the new one works on macOS. Do you have any hints for that? Thank you! Please correct me if I misunderstand anything.

**Comment by haochenuw** [comment]
Looking at it again it seems the apply_galois on line 108 is not needed. Have you tried deleting that and see if it still works on macOS? 

For the ubuntu case, one thing to try is to make a minimal example which triggers the segfault, which you can do by keep deleting lines from the function. Then you can submit it to the SEAL repository as an issue.

**Comment by kzhong130** [comment]
Yes, after deleting that line, it still works on macOS. 

I will submit an issue to SEAL, thank you!

**Pull request merged**
